qcacld-3.0: Fix build error when !CONFIG_DEBUG_FS Signed-off-by: LibXZR <i@xzr.moe>
I don't know why the “CONFIG_DEBUG_FS=y” option is missing from the kona-perf_defconfig in this open-source environment.

I build the kernel meet this error:

../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:5612:2: error: implicit declaration of function 'hdd_debugfs_process_mib_stats' [-Werror,-Wimplicit-function-declaration]
        hdd_debugfs_process_mib_stats(adapter, stats);
        ^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:5612:2: note: did you mean 'hdd_debugfs_process_ll_stats'?
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:1196:13: note: 'hdd_debugfs_process_ll_stats' declared here
static void hdd_debugfs_process_ll_stats(struct hdd_adapter *adapter,
            ^
1 error generated.

fuck!!!